export enum TABLE_NAME {
  __PENDING_USERS = 'pending_users',
  __USERS = 'users',
  __TEAM = 'team',
  __RELATION_TEAM_USERS = 'relation_team_users',
  __SALARY = 'users_salary',
  __STACK = 'stack',
  __LEVEL_1_LIST = 'employee_role_users',
  __LEVEL_2_LIST = 'leader_role_users',
  __LEVEL_3_LIST = 'sub_admin_role_users',
  __LEVEL_4_LIST = 'admin_role_users',
  __PROJECT = 'project',
  __KANBAN = 'kanban',
  __ISSUE = 'issue',
  __ROLE_PERMISSION = 'role_permission',
  __PROFILE = 'profile',
  __FIELD = 'field',
  __RELATION_PROJECT_STACK = 'relation_project_stack',
}
